#!/bin/bash

# /usr/lib/jvm/java-11-openjdk/bin/java \n
# --add-opens java.base/java.lang=com.google.guice \
# --add-reads javafx.base=ALL-UNNAMED \
# --add-reads javafx.graphics=ALL-UNNAMED \
# --add-modules javafx.base,javafx.graphics \

# /usr/lib/jvm/java-11-openjdk/bin/jdeps \
#     --module-path  /home/ttmdear/.m2/repository/org/openjfx/javafx-base/11/javafx-base-11-linux.jar:/home/ttmdear/.m2/repository/org/openjfx/javafx-graphics/13/javafx-graphics-13-linux.jar:/home/ttmdear/workspace-local/httpio/target/classes:/home/ttmdear/.m2/repository/com/google/inject/guice/4.2.2/guice-4.2.2.jar:/home/ttmdear/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/home/ttmdear/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/home/ttmdear/.m2/repository/com/google/guava/guava/25.1-android/guava-25.1-android.jar:/home/ttmdear/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/home/ttmdear/.m2/repository/org/checkerframework/checker-compat-qual/2.0.0/checker-compat-qual-2.0.0.jar:/home/ttmdear/.m2/repository/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar:/home/ttmdear/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar:/home/ttmdear/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar:/home/ttmdear/.m2/repository/cglib/cglib/3.3.0/cglib-3.3.0.jar:/home/ttmdear/.m2/repository/org/ow2/asm/asm/7.1/asm-7.1.jar:/home/ttmdear/.m2/repository/org/apache/commons/commons-text/1.7/commons-text-1.7.jar:/home/ttmdear/.m2/repository/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar:/home/ttmdear/.m2/repository/org/jetbrains/annotations/17.0.0/annotations-17.0.0.jar:/home/ttmdear/.m2/repository/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar:/home/ttmdear/.m2/repository/org/openjfx/javafx-controls/13/javafx-controls-13.jar:/home/ttmdear/.m2/repository/org/openjfx/javafx-controls/13/javafx-controls-13-linux.jar:/home/ttmdear/.m2/repository/org/openjfx/javafx-graphics/13/javafx-graphics-13.jar:/home/ttmdear/.m2/repository/org/openjfx/javafx-fxml/13/javafx-fxml-13.jar:/home/ttmdear/.m2/repository/org/openjfx/javafx-fxml/13/javafx-fxml-13-linux.jar:/home/ttmdear/.m2/repository/org/controlsfx/controlsfx/11.0.0/controlsfx-11.0.0.jar:/home/ttmdear/.m2/repository/org/openjfx/javafx-base/11/javafx-base-11.jar:/home/ttmdear/.m2/repository/org/openjfx/javafx-media/11/javafx-media-11.jar:/home/ttmdear/.m2/repository/org/openjfx/javafx-media/11/javafx-media-11-linux.jar:/home/ttmdear/.m2/repository/org/openjfx/javafx-web/11/javafx-web-11.jar:/home/ttmdear/.m2/repository/org/openjfx/javafx-web/11/javafx-web-11-linux.jar\
#     -s \
#     --module com.httpio

# /usr/lib/jvm/java-11-openjdk/bin/jlink\
#     --module-path  /home/ttmdear/.m2/repository/org/openjfx/javafx-base/11/javafx-base-11-linux.jar:/home/ttmdear/.m2/repository/org/openjfx/javafx-graphics/13/javafx-graphics-13-linux.jar:/home/ttmdear/workspace-local/httpio/target/classes:/home/ttmdear/.m2/repository/com/google/inject/guice/4.2.2/guice-4.2.2.jar:/home/ttmdear/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/home/ttmdear/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/home/ttmdear/.m2/repository/com/google/guava/guava/25.1-android/guava-25.1-android.jar:/home/ttmdear/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/home/ttmdear/.m2/repository/org/checkerframework/checker-compat-qual/2.0.0/checker-compat-qual-2.0.0.jar:/home/ttmdear/.m2/repository/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar:/home/ttmdear/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar:/home/ttmdear/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar:/home/ttmdear/.m2/repository/cglib/cglib/3.3.0/cglib-3.3.0.jar:/home/ttmdear/.m2/repository/org/ow2/asm/asm/7.1/asm-7.1.jar:/home/ttmdear/.m2/repository/org/apache/commons/commons-text/1.7/commons-text-1.7.jar:/home/ttmdear/.m2/repository/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar:/home/ttmdear/.m2/repository/org/jetbrains/annotations/17.0.0/annotations-17.0.0.jar:/home/ttmdear/.m2/repository/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar:/home/ttmdear/.m2/repository/org/openjfx/javafx-controls/13/javafx-controls-13.jar:/home/ttmdear/.m2/repository/org/openjfx/javafx-controls/13/javafx-controls-13-linux.jar:/home/ttmdear/.m2/repository/org/openjfx/javafx-graphics/13/javafx-graphics-13.jar:/home/ttmdear/.m2/repository/org/openjfx/javafx-fxml/13/javafx-fxml-13.jar:/home/ttmdear/.m2/repository/org/openjfx/javafx-fxml/13/javafx-fxml-13-linux.jar:/home/ttmdear/.m2/repository/org/controlsfx/controlsfx/11.0.0/controlsfx-11.0.0.jar:/home/ttmdear/.m2/repository/org/openjfx/javafx-base/11/javafx-base-11.jar:/home/ttmdear/.m2/repository/org/openjfx/javafx-media/11/javafx-media-11.jar:/home/ttmdear/.m2/repository/org/openjfx/javafx-media/11/javafx-media-11-linux.jar:/home/ttmdear/.m2/repository/org/openjfx/javafx-web/11/javafx-web-11.jar:/home/ttmdear/.m2/repository/org/openjfx/javafx-web/11/javafx-web-11-linux.jar\
#     --verbose\
#     --add-modules com.httpio\
#     --output "httpio.1.0.0-pre-alpha"

/usr/lib/jvm/java-11-openjdk/bin/jar\
    --create\
    --main-class com.httpio.app.App\
    --file "httpio.1.0.0-pre-alpha.jar" .

